DEFAULT_ACCOUNT_TYPE = "simple"
SAVINGS_ACCOUNT_TYPE = "savings"
BONUS_ACCOUNT_TYPE = "bonus"
BONUS_ACCOUNT_INITIAL_POINTS = 10

ACCOUNT_TYPE_LABELS = {
    DEFAULT_ACCOUNT_TYPE: "Conta Simples",
    SAVINGS_ACCOUNT_TYPE: "Conta Poupança",
    BONUS_ACCOUNT_TYPE: "Conta Bônus",
}
